import '../models/surah.dart';

class QuranData {
  static final List<Surah> surahs = [
    Surah(
      number: 1,
      name: 'الفاتحة',
      englishName: 'Al-Fatiha',
      englishNameTranslation: 'The Opening',
      numberOfAyahs: 7,
      revelationType: 'Meccan',
      startPage: 1,
    ),
    Surah(
      number: 2,
      name: 'البقرة',
      englishName: 'Al-Baqarah',
      englishNameTranslation: 'The Cow',
      numberOfAyahs: 286,
      revelationType: 'Medinan',
      startPage: 2,
    ),
    Surah(
      number: 3,
      name: 'آل عمران',
      englishName: 'Al-Imran',
      englishNameTranslation: 'The Family of Imran',
      numberOfAyahs: 200,
      revelationType: 'Medinan',
      startPage: 50,
    ),
    Surah(
      number: 4,
      name: 'النساء',
      englishName: 'An-Nisa',
      englishNameTranslation: 'The Women',
      numberOfAyahs: 176,
      revelationType: 'Medinan',
      startPage: 77,
    ),
    Surah(
      number: 5,
      name: 'المائدة',
      englishName: 'Al-Ma\'idah',
      englishNameTranslation: 'The Table Spread',
      numberOfAyahs: 120,
      revelationType: 'Medinan',
      startPage: 106,
    ),
    Surah(
      number: 6,
      name: 'الأنعام',
      englishName: 'Al-An\'am',
      englishNameTranslation: 'The Cattle',
      numberOfAyahs: 165,
      revelationType: 'Meccan',
      startPage: 128,
    ),
    Surah(
      number: 7,
      name: 'الأعراف',
      englishName: 'Al-A\'raf',
      englishNameTranslation: 'The Heights',
      numberOfAyahs: 206,
      revelationType: 'Meccan',
      startPage: 151,
    ),
    Surah(
      number: 8,
      name: 'الأنفال',
      englishName: 'Al-Anfal',
      englishNameTranslation: 'The Spoils of War',
      numberOfAyahs: 75,
      revelationType: 'Medinan',
      startPage: 177,
    ),
    Surah(
      number: 9,
      name: 'التوبة',
      englishName: 'At-Tawbah',
      englishNameTranslation: 'The Repentance',
      numberOfAyahs: 129,
      revelationType: 'Medinan',
      startPage: 187,
    ),
    Surah(
      number: 10,
      name: 'يونس',
      englishName: 'Yunus',
      englishNameTranslation: 'Jonah',
      numberOfAyahs: 109,
      revelationType: 'Meccan',
      startPage: 208,
    ),
    Surah(
      number: 11,
      name: 'هود',
      englishName: 'Hud',
      englishNameTranslation: 'Hud',
      numberOfAyahs: 123,
      revelationType: 'Meccan',
      startPage: 221,
    ),
    Surah(
      number: 12,
      name: 'يوسف',
      englishName: 'Yusuf',
      englishNameTranslation: 'Joseph',
      numberOfAyahs: 111,
      revelationType: 'Meccan',
      startPage: 235,
    ),
    Surah(
      number: 13,
      name: 'الرعد',
      englishName: 'Ar-Ra\'d',
      englishNameTranslation: 'The Thunder',
      numberOfAyahs: 43,
      revelationType: 'Medinan',
      startPage: 249,
    ),
    Surah(
      number: 14,
      name: 'إبراهيم',
      englishName: 'Ibrahim',
      englishNameTranslation: 'Abraham',
      numberOfAyahs: 52,
      revelationType: 'Meccan',
      startPage: 255,
    ),
    Surah(
      number: 15,
      name: 'الحجر',
      englishName: 'Al-Hijr',
      englishNameTranslation: 'The Rocky Tract',
      numberOfAyahs: 99,
      revelationType: 'Meccan',
      startPage: 262,
    ),
    Surah(
      number: 16,
      name: 'النحل',
      englishName: 'An-Nahl',
      englishNameTranslation: 'The Bee',
      numberOfAyahs: 128,
      revelationType: 'Meccan',
      startPage: 267,
    ),
    Surah(
      number: 17,
      name: 'الإسراء',
      englishName: 'Al-Isra',
      englishNameTranslation: 'The Night Journey',
      numberOfAyahs: 111,
      revelationType: 'Meccan',
      startPage: 282,
    ),
    Surah(
      number: 18,
      name: 'الكهف',
      englishName: 'Al-Kahf',
      englishNameTranslation: 'The Cave',
      numberOfAyahs: 110,
      revelationType: 'Meccan',
      startPage: 293,
    ),
    Surah(
      number: 19,
      name: 'مريم',
      englishName: 'Maryam',
      englishNameTranslation: 'Mary',
      numberOfAyahs: 98,
      revelationType: 'Meccan',
      startPage: 305,
    ),
    Surah(
      number: 20,
      name: 'طه',
      englishName: 'Ta-Ha',
      englishNameTranslation: 'Ta-Ha',
      numberOfAyahs: 135,
      revelationType: 'Meccan',
      startPage: 312,
    ),
    Surah(
      number: 21,
      name: 'الأنبياء',
      englishName: 'Al-Anbiya',
      englishNameTranslation: 'The Prophets',
      numberOfAyahs: 112,
      revelationType: 'Meccan',
      startPage: 322,
    ),
    Surah(
      number: 22,
      name: 'الحج',
      englishName: 'Al-Hajj',
      englishNameTranslation: 'The Pilgrimage',
      numberOfAyahs: 78,
      revelationType: 'Medinan',
      startPage: 332,
    ),
    Surah(
      number: 23,
      name: 'المؤمنون',
      englishName: 'Al-Mu\'minun',
      englishNameTranslation: 'The Believers',
      numberOfAyahs: 118,
      revelationType: 'Meccan',
      startPage: 342,
    ),
    Surah(
      number: 24,
      name: 'النور',
      englishName: 'An-Nur',
      englishNameTranslation: 'The Light',
      numberOfAyahs: 64,
      revelationType: 'Medinan',
      startPage: 350,
    ),
    Surah(
      number: 25,
      name: 'الفرقان',
      englishName: 'Al-Furqan',
      englishNameTranslation: 'The Criterion',
      numberOfAyahs: 77,
      revelationType: 'Meccan',
      startPage: 359,
    ),
    Surah(
      number: 26,
      name: 'الشعراء',
      englishName: 'Ash-Shu\'ara',
      englishNameTranslation: 'The Poets',
      numberOfAyahs: 227,
      revelationType: 'Meccan',
      startPage: 367,
    ),
    Surah(
      number: 27,
      name: 'النمل',
      englishName: 'An-Naml',
      englishNameTranslation: 'The Ant',
      numberOfAyahs: 93,
      revelationType: 'Meccan',
      startPage: 377,
    ),
    Surah(
      number: 28,
      name: 'القصص',
      englishName: 'Al-Qasas',
      englishNameTranslation: 'The Stories',
      numberOfAyahs: 88,
      revelationType: 'Meccan',
      startPage: 385,
    ),
    Surah(
      number: 29,
      name: 'العنكبوت',
      englishName: 'Al-Ankabut',
      englishNameTranslation: 'The Spider',
      numberOfAyahs: 69,
      revelationType: 'Meccan',
      startPage: 396,
    ),
    Surah(
      number: 30,
      name: 'الروم',
      englishName: 'Ar-Rum',
      englishNameTranslation: 'The Romans',
      numberOfAyahs: 60,
      revelationType: 'Meccan',
      startPage: 404,
    ),
    Surah(
      number: 31,
      name: 'لقمان',
      englishName: 'Luqman',
      englishNameTranslation: 'Luqman',
      numberOfAyahs: 34,
      revelationType: 'Meccan',
      startPage: 411,
    ),
    Surah(
      number: 32,
      name: 'السجدة',
      englishName: 'As-Sajdah',
      englishNameTranslation: 'The Prostration',
      numberOfAyahs: 30,
      revelationType: 'Meccan',
      startPage: 415,
    ),
    Surah(
      number: 33,
      name: 'الأحزاب',
      englishName: 'Al-Ahzab',
      englishNameTranslation: 'The Combined Forces',
      numberOfAyahs: 73,
      revelationType: 'Medinan',
      startPage: 418,
    ),
    Surah(
      number: 34,
      name: 'سبأ',
      englishName: 'Saba',
      englishNameTranslation: 'Sheba',
      numberOfAyahs: 54,
      revelationType: 'Meccan',
      startPage: 428,
    ),
    Surah(
      number: 35,
      name: 'فاطر',
      englishName: 'Fatir',
      englishNameTranslation: 'The Originator',
      numberOfAyahs: 45,
      revelationType: 'Meccan',
      startPage: 434,
    ),
    Surah(
      number: 36,
      name: 'يس',
      englishName: 'Ya-Sin',
      englishNameTranslation: 'Ya-Sin',
      numberOfAyahs: 83,
      revelationType: 'Meccan',
      startPage: 440,
    ),
    Surah(
      number: 37,
      name: 'الصافات',
      englishName: 'As-Saffat',
      englishNameTranslation: 'Those Ranged in Ranks',
      numberOfAyahs: 182,
      revelationType: 'Meccan',
      startPage: 446,
    ),
    Surah(
      number: 38,
      name: 'ص',
      englishName: 'Sad',
      englishNameTranslation: 'Sad',
      numberOfAyahs: 88,
      revelationType: 'Meccan',
      startPage: 453,
    ),
    Surah(
      number: 39,
      name: 'الزمر',
      englishName: 'Az-Zumar',
      englishNameTranslation: 'The Troops',
      numberOfAyahs: 75,
      revelationType: 'Meccan',
      startPage: 458,
    ),
    Surah(
      number: 40,
      name: 'غافر',
      englishName: 'Ghafir',
      englishNameTranslation: 'The Forgiver',
      numberOfAyahs: 85,
      revelationType: 'Meccan',
      startPage: 467,
    ),
    Surah(
      number: 41,
      name: 'فصلت',
      englishName: 'Fussilat',
      englishNameTranslation: 'Explained in Detail',
      numberOfAyahs: 54,
      revelationType: 'Meccan',
      startPage: 477,
    ),
    Surah(
      number: 42,
      name: 'الشورى',
      englishName: 'Ash-Shura',
      englishNameTranslation: 'The Consultation',
      numberOfAyahs: 53,
      revelationType: 'Meccan',
      startPage: 483,
    ),
    Surah(
      number: 43,
      name: 'الزخرف',
      englishName: 'Az-Zukhruf',
      englishNameTranslation: 'The Ornaments of Gold',
      numberOfAyahs: 89,
      revelationType: 'Meccan',
      startPage: 489,
    ),
    Surah(
      number: 44,
      name: 'الدخان',
      englishName: 'Ad-Dukhan',
      englishNameTranslation: 'The Smoke',
      numberOfAyahs: 59,
      revelationType: 'Meccan',
      startPage: 496,
    ),
    Surah(
      number: 45,
      name: 'الجاثية',
      englishName: 'Al-Jathiyah',
      englishNameTranslation: 'The Kneeling',
      numberOfAyahs: 37,
      revelationType: 'Meccan',
      startPage: 499,
    ),
    Surah(
      number: 46,
      name: 'الأحقاف',
      englishName: 'Al-Ahqaf',
      englishNameTranslation: 'The Sand-Dunes',
      numberOfAyahs: 35,
      revelationType: 'Meccan',
      startPage: 502,
    ),
    Surah(
      number: 47,
      name: 'محمد',
      englishName: 'Muhammad',
      englishNameTranslation: 'Muhammad',
      numberOfAyahs: 38,
      revelationType: 'Medinan',
      startPage: 507,
    ),
    Surah(
      number: 48,
      name: 'الفتح',
      englishName: 'Al-Fath',
      englishNameTranslation: 'The Victory',
      numberOfAyahs: 29,
      revelationType: 'Medinan',
      startPage: 511,
    ),
    Surah(
      number: 49,
      name: 'الحجرات',
      englishName: 'Al-Hujurat',
      englishNameTranslation: 'The Rooms',
      numberOfAyahs: 18,
      revelationType: 'Medinan',
      startPage: 515,
    ),
    Surah(
      number: 50,
      name: 'ق',
      englishName: 'Qaf',
      englishNameTranslation: 'Qaf',
      numberOfAyahs: 45,
      revelationType: 'Meccan',
      startPage: 518,
    ),
    Surah(
      number: 51,
      name: 'الذاريات',
      englishName: 'Adh-Dhariyat',
      englishNameTranslation: 'The Winnowing Winds',
      numberOfAyahs: 60,
      revelationType: 'Meccan',
      startPage: 520,
    ),
    Surah(
      number: 52,
      name: 'الطور',
      englishName: 'At-Tur',
      englishNameTranslation: 'The Mount',
      numberOfAyahs: 49,
      revelationType: 'Meccan',
      startPage: 523,
    ),
    Surah(
      number: 53,
      name: 'النجم',
      englishName: 'An-Najm',
      englishNameTranslation: 'The Star',
      numberOfAyahs: 62,
      revelationType: 'Meccan',
      startPage: 526,
    ),
    Surah(
      number: 54,
      name: 'القمر',
      englishName: 'Al-Qamar',
      englishNameTranslation: 'The Moon',
      numberOfAyahs: 55,
      revelationType: 'Meccan',
      startPage: 529,
    ),
    Surah(
      number: 55,
      name: 'الرحمن',
      englishName: 'Ar-Rahman',
      englishNameTranslation: 'The Most Gracious',
      numberOfAyahs: 78,
      revelationType: 'Medinan',
      startPage: 531,
    ),
    Surah(
      number: 56,
      name: 'الواقعة',
      englishName: 'Al-Waqi\'ah',
      englishNameTranslation: 'The Inevitable Event',
      numberOfAyahs: 96,
      revelationType: 'Meccan',
      startPage: 534,
    ),
    Surah(
      number: 57,
      name: 'الحديد',
      englishName: 'Al-Hadid',
      englishNameTranslation: 'The Iron',
      numberOfAyahs: 29,
      revelationType: 'Medinan',
      startPage: 538,
    ),
    Surah(
      number: 58,
      name: 'المجادلة',
      englishName: 'Al-Mujadila',
      englishNameTranslation: 'The Pleading Woman',
      numberOfAyahs: 22,
      revelationType: 'Medinan',
      startPage: 545,
    ),
    Surah(
      number: 59,
      name: 'الحشر',
      englishName: 'Al-Hashr',
      englishNameTranslation: 'The Gathering',
      numberOfAyahs: 24,
      revelationType: 'Medinan',
      startPage: 548,
    ),
    Surah(
      number: 60,
      name: 'الممتحنة',
      englishName: 'Al-Mumtahanah',
      englishNameTranslation: 'The Woman to be Examined',
      numberOfAyahs: 13,
      revelationType: 'Medinan',
      startPage: 551,
    ),
    Surah(
      number: 61,
      name: 'الصف',
      englishName: 'As-Saff',
      englishNameTranslation: 'The Ranks',
      numberOfAyahs: 14,
      revelationType: 'Medinan',
      startPage: 554,
    ),
    Surah(
      number: 62,
      name: 'الجمعة',
      englishName: 'Al-Jumu\'ah',
      englishNameTranslation: 'The Friday',
      numberOfAyahs: 11,
      revelationType: 'Medinan',
      startPage: 556,
    ),
    Surah(
      number: 63,
      name: 'المنافقون',
      englishName: 'Al-Munafiqun',
      englishNameTranslation: 'The Hypocrites',
      numberOfAyahs: 11,
      revelationType: 'Medinan',
      startPage: 557,
    ),
    Surah(
      number: 64,
      name: 'التغابن',
      englishName: 'At-Taghabun',
      englishNameTranslation: 'The Mutual Disillusion',
      numberOfAyahs: 18,
      revelationType: 'Medinan',
      startPage: 559,
    ),
    Surah(
      number: 65,
      name: 'الطلاق',
      englishName: 'At-Talaq',
      englishNameTranslation: 'The Divorce',
      numberOfAyahs: 12,
      revelationType: 'Medinan',
      startPage: 560,
    ),
    Surah(
      number: 66,
      name: 'التحريم',
      englishName: 'At-Tahrim',
      englishNameTranslation: 'The Prohibiting',
      numberOfAyahs: 12,
      revelationType: 'Medinan',
      startPage: 563,
    ),
    Surah(
      number: 67,
      name: 'الملك',
      englishName: 'Al-Mulk',
      englishNameTranslation: 'The Sovereignty',
      numberOfAyahs: 30,
      revelationType: 'Meccan',
      startPage: 564,
    ),
    Surah(
      number: 68,
      name: 'القلم',
      englishName: 'Al-Qalam',
      englishNameTranslation: 'The Pen',
      numberOfAyahs: 52,
      revelationType: 'Meccan',
      startPage: 566,
    ),
    Surah(
      number: 69,
      name: 'الحاقة',
      englishName: 'Al-Haqqah',
      englishNameTranslation: 'The Inevitable Reality',
      numberOfAyahs: 52,
      revelationType: 'Meccan',
      startPage: 568,
    ),
    Surah(
      number: 70,
      name: 'المعارج',
      englishName: 'Al-Ma\'arij',
      englishNameTranslation: 'The Ascending Stairways',
      numberOfAyahs: 44,
      revelationType: 'Meccan',
      startPage: 570,
    ),
    Surah(
      number: 71,
      name: 'نوح',
      englishName: 'Nuh',
      englishNameTranslation: 'Noah',
      numberOfAyahs: 28,
      revelationType: 'Meccan',
      startPage: 571,
    ),
    Surah(
      number: 72,
      name: 'الجن',
      englishName: 'Al-Jinn',
      englishNameTranslation: 'The Jinn',
      numberOfAyahs: 28,
      revelationType: 'Meccan',
      startPage: 572,
    ),
    Surah(
      number: 73,
      name: 'المزمل',
      englishName: 'Al-Muzzammil',
      englishNameTranslation: 'The Enshrouded One',
      numberOfAyahs: 20,
      revelationType: 'Meccan',
      startPage: 574,
    ),
    Surah(
      number: 74,
      name: 'المدثر',
      englishName: 'Al-Muddaththir',
      englishNameTranslation: 'The Cloaked One',
      numberOfAyahs: 56,
      revelationType: 'Meccan',
      startPage: 575,
    ),
    Surah(
      number: 75,
      name: 'القيامة',
      englishName: 'Al-Qiyamah',
      englishNameTranslation: 'The Resurrection',
      numberOfAyahs: 40,
      revelationType: 'Meccan',
      startPage: 577,
    ),
    Surah(
      number: 76,
      name: 'الإنسان',
      englishName: 'Al-Insan',
      englishNameTranslation: 'Man',
      numberOfAyahs: 31,
      revelationType: 'Medinan',
      startPage: 578,
    ),
    Surah(
      number: 77,
      name: 'المرسلات',
      englishName: 'Al-Mursalat',
      englishNameTranslation: 'The Emissaries',
      numberOfAyahs: 50,
      revelationType: 'Meccan',
      startPage: 580,
    ),
    Surah(
      number: 78,
      name: 'النبأ',
      englishName: 'An-Naba',
      englishNameTranslation: 'The Tidings',
      numberOfAyahs: 40,
      revelationType: 'Meccan',
      startPage: 582,
    ),
    Surah(
      number: 79,
      name: 'النازعات',
      englishName: 'An-Nazi\'at',
      englishNameTranslation: 'Those Who Drag Forth',
      numberOfAyahs: 46,
      revelationType: 'Meccan',
      startPage: 583,
    ),
    Surah(
      number: 80,
      name: 'عبس',
      englishName: 'Abasa',
      englishNameTranslation: 'He Frowned',
      numberOfAyahs: 42,
      revelationType: 'Meccan',
      startPage: 585,
    ),
    Surah(
      number: 81,
      name: 'التكوير',
      englishName: 'At-Takwir',
      englishNameTranslation: 'The Overthrowing',
      numberOfAyahs: 29,
      revelationType: 'Meccan',
      startPage: 586,
    ),
    Surah(
      number: 82,
      name: 'الانفطار',
      englishName: 'Al-Infitar',
      englishNameTranslation: 'The Cleaving Asunder',
      numberOfAyahs: 19,
      revelationType: 'Meccan',
      startPage: 587,
    ),
    Surah(
      number: 83,
      name: 'المطففين',
      englishName: 'Al-Mutaffifin',
      englishNameTranslation: 'The Defrauders',
      numberOfAyahs: 36,
      revelationType: 'Meccan',
      startPage: 587,
    ),
    Surah(
      number: 84,
      name: 'الانشقاق',
      englishName: 'Al-Inshiqaq',
      englishNameTranslation: 'The Sundering',
      numberOfAyahs: 25,
      revelationType: 'Meccan',
      startPage: 589,
    ),
    Surah(
      number: 85,
      name: 'البروج',
      englishName: 'Al-Buruj',
      englishNameTranslation: 'The Constellations',
      numberOfAyahs: 22,
      revelationType: 'Meccan',
      startPage: 590,
    ),
    Surah(
      number: 86,
      name: 'الطارق',
      englishName: 'At-Tariq',
      englishNameTranslation: 'The Nightcomer',
      numberOfAyahs: 17,
      revelationType: 'Meccan',
      startPage: 591,
    ),
    Surah(
      number: 87,
      name: 'الأعلى',
      englishName: 'Al-A\'la',
      englishNameTranslation: 'The Most High',
      numberOfAyahs: 19,
      revelationType: 'Meccan',
      startPage: 591,
    ),
    Surah(
      number: 88,
      name: 'الغاشية',
      englishName: 'Al-Ghashiyah',
      englishNameTranslation: 'The Overwhelming',
      numberOfAyahs: 26,
      revelationType: 'Meccan',
      startPage: 592,
    ),
    Surah(
      number: 89,
      name: 'الفجر',
      englishName: 'Al-Fajr',
      englishNameTranslation: 'The Dawn',
      numberOfAyahs: 30,
      revelationType: 'Meccan',
      startPage: 593,
    ),
    Surah(
      number: 90,
      name: 'البلد',
      englishName: 'Al-Balad',
      englishNameTranslation: 'The City',
      numberOfAyahs: 20,
      revelationType: 'Meccan',
      startPage: 594,
    ),
    Surah(
      number: 91,
      name: 'الشمس',
      englishName: 'Ash-Shams',
      englishNameTranslation: 'The Sun',
      numberOfAyahs: 15,
      revelationType: 'Meccan',
      startPage: 595,
    ),
    Surah(
      number: 92,
      name: 'الليل',
      englishName: 'Al-Layl',
      englishNameTranslation: 'The Night',
      numberOfAyahs: 21,
      revelationType: 'Meccan',
      startPage: 595,
    ),
    Surah(
      number: 93,
      name: 'الضحى',
      englishName: 'Ad-Duha',
      englishNameTranslation: 'The Morning Hours',
      numberOfAyahs: 11,
      revelationType: 'Meccan',
      startPage: 596,
    ),
    Surah(
      number: 94,
      name: 'الشرح',
      englishName: 'Al-Inshirah',
      englishNameTranslation: 'The Relief',
      numberOfAyahs: 8,
      revelationType: 'Meccan',
      startPage: 596,
    ),
    Surah(
      number: 95,
      name: 'التين',
      englishName: 'At-Tin',
      englishNameTranslation: 'The Fig',
      numberOfAyahs: 8,
      revelationType: 'Meccan',
      startPage: 597,
    ),
    Surah(
      number: 96,
      name: 'العلق',
      englishName: 'Al-\'Alaq',
      englishNameTranslation: 'The Clot',
      numberOfAyahs: 19,
      revelationType: 'Meccan',
      startPage: 597,
    ),
    Surah(
      number: 97,
      name: 'القدر',
      englishName: 'Al-Qadr',
      englishNameTranslation: 'The Power',
      numberOfAyahs: 5,
      revelationType: 'Meccan',
      startPage: 598,
    ),
    Surah(
      number: 98,
      name: 'البينة',
      englishName: 'Al-Bayyinah',
      englishNameTranslation: 'The Clear Proof',
      numberOfAyahs: 8,
      revelationType: 'Medinan',
      startPage: 598,
    ),
    Surah(
      number: 99,
      name: 'الزلزلة',
      englishName: 'Az-Zalzalah',
      englishNameTranslation: 'The Earthquake',
      numberOfAyahs: 8,
      revelationType: 'Medinan',
      startPage: 599,
    ),
    Surah(
      number: 100,
      name: 'العاديات',
      englishName: 'Al-\'Adiyat',
      englishNameTranslation: 'The Chargers',
      numberOfAyahs: 11,
      revelationType: 'Meccan',
      startPage: 599,
    ),
    Surah(
      number: 101,
      name: 'القارعة',
      englishName: 'Al-Qari\'ah',
      englishNameTranslation: 'The Striking Calamity',
      numberOfAyahs: 11,
      revelationType: 'Meccan',
      startPage: 600,
    ),
    Surah(
      number: 102,
      name: 'التكاثر',
      englishName: 'At-Takathur',
      englishNameTranslation: 'The Rivalry in Worldly Increase',
      numberOfAyahs: 8,
      revelationType: 'Meccan',
      startPage: 600,
    ),
    Surah(
      number: 103,
      name: 'العصر',
      englishName: 'Al-\'Asr',
      englishNameTranslation: 'The Time',
      numberOfAyahs: 3,
      revelationType: 'Meccan',
      startPage: 601,
    ),
    Surah(
      number: 104,
      name: 'الهمزة',
      englishName: 'Al-Humazah',
      englishNameTranslation: 'The Slanderer',
      numberOfAyahs: 9,
      revelationType: 'Meccan',
      startPage: 601,
    ),
    Surah(
      number: 105,
      name: 'الفيل',
      englishName: 'Al-Fil',
      englishNameTranslation: 'The Elephant',
      numberOfAyahs: 5,
      revelationType: 'Meccan',
      startPage: 601,
    ),
    Surah(
      number: 106,
      name: 'قريش',
      englishName: 'Quraish',
      englishNameTranslation: 'Quraish',
      numberOfAyahs: 4,
      revelationType: 'Meccan',
      startPage: 602,
    ),
    Surah(
      number: 107,
      name: 'الماعون',
      englishName: 'Al-Ma\'un',
      englishNameTranslation: 'The Small Kindnesses',
      numberOfAyahs: 7,
      revelationType: 'Meccan',
      startPage: 602,
    ),
    Surah(
      number: 108,
      name: 'الكوثر',
      englishName: 'Al-Kawthar',
      englishNameTranslation: 'The Abundance',
      numberOfAyahs: 3,
      revelationType: 'Meccan',
      startPage: 602,
    ),
    Surah(
      number: 109,
      name: 'الكافرون',
      englishName: 'Al-Kafirun',
      englishNameTranslation: 'The Disbelievers',
      numberOfAyahs: 6,
      revelationType: 'Meccan',
      startPage: 603,
    ),
    Surah(
      number: 110,
      name: 'النصر',
      englishName: 'An-Nasr',
      englishNameTranslation: 'The Divine Support',
      numberOfAyahs: 3,
      revelationType: 'Medinan',
      startPage: 603,
    ),
    Surah(
      number: 111,
      name: 'المسد',
      englishName: 'Al-Masad',
      englishNameTranslation: 'The Palm Fibre',
      numberOfAyahs: 5,
      revelationType: 'Meccan',
      startPage: 603,
    ),
    Surah(
      number: 112,
      name: 'الإخلاص',
      englishName: 'Al-Ikhlas',
      englishNameTranslation: 'The Sincerity',
      numberOfAyahs: 4,
      revelationType: 'Meccan',
      startPage: 604,
    ),
    Surah(
      number: 113,
      name: 'الفلق',
      englishName: 'Al-Falaq',
      englishNameTranslation: 'The Daybreak',
      numberOfAyahs: 5,
      revelationType: 'Meccan',
      startPage: 604,
    ),
    Surah(
      number: 114,
      name: 'الناس',
      englishName: 'An-Nas',
      englishNameTranslation: 'Mankind',
      numberOfAyahs: 6,
      revelationType: 'Meccan',
      startPage: 604,
    ),
  ];
}
